version: "3"
services:
  auth_mysql:
    container_name: auth_db
    hostname: auth_db
    image: mysql:8.0.26
    ports:
      - "${AUTH_MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${AUTH_DB}
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_PASSWORD}
    networks:
      - auth_net

  redis:
    image: redis
    container_name: auth_redis
    hostname: redis
    expose:
      - 6379
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - auth_net

networks:
  auth_net:
    external:
      name: auth_net
